### ISSUE TITLE
Compatibility with Safari

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#27]
The background seems to be continuously processing, especially if you resize the browser. Can be seen on iOS 9.

To quote @idoan:

> Yes it still stands, 3/5 of the page is stretched header image, the remaining 2/5 is the content . But this is better than previous case, as I can now scroll to the bottom to see the content.

CC @anweshm4 (moved the issue here)

**Comment by idoan** [comment]
ok, here are the screenshots:

http://imgur.com/7onXmE7

and look at the position of the scroll

http://imgur.com/B1njBJc

the background image stretches up to the %60 percent of the page. 

device: ipad2/iphone, 
os: ios 7. 
browser: same in chrome and safari. 

my offer: if this problem is specific to ios 7, just ignore, this os is quite old and already obsolete

**Comment by bebraw** [comment]
Thanks! I'm doing some CSS trickery there so that could explain it. 👍

**Comment by sapegin** [comment]
I guess it’s not relevant anymore?

**Comment by bebraw** [comment]
Let’s close.

@idoan Feel free to comment.
